# Generated by Django 4.2.16 on 2024-12-19 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210426_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='units',
            field=models.CharField(default='pieces', max_length=50),
            preserve_default=False,
        ),
    ]
