# Generated by Django 4.2.16 on 2024-12-19 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='units',
            field=models.CharField(default='kg', max_length=50),
        ),
    ]
